// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package profiles

import (
	"context"
	"database/sql"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (username, name, bio, link, avatar, private, user_id, created_at, updated_at) 
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, username, name, bio, link, avatar, private, user_id, created_at, updated_at
`

type CreateProfileParams struct {
	Username  string
	Name      sql.NullString
	Bio       sql.NullString
	Link      sql.NullString
	Avatar    sql.NullString
	Private   sql.NullInt64
	UserID    int64
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.Username,
		arg.Name,
		arg.Bio,
		arg.Link,
		arg.Avatar,
		arg.Private,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Bio,
		&i.Link,
		&i.Avatar,
		&i.Private,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileAvatarFromUserId = `-- name: GetProfileAvatarFromUserId :one
SELECT avatar FROM profiles WHERE user_id = ?
`

func (q *Queries) GetProfileAvatarFromUserId(ctx context.Context, userID int64) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getProfileAvatarFromUserId, userID)
	var avatar sql.NullString
	err := row.Scan(&avatar)
	return avatar, err
}

const getProfileFromUserId = `-- name: GetProfileFromUserId :one
SELECT id, username, name, bio, link, avatar, private, user_id, created_at, updated_at FROM profiles WHERE user_id = ?
`

func (q *Queries) GetProfileFromUserId(ctx context.Context, userID int64) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileFromUserId, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Bio,
		&i.Link,
		&i.Avatar,
		&i.Private,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles 
SET username = ?, name = ?, bio = ?, link = ?, avatar = ?, private = ?, updated_at = ? 
WHERE user_id = ? 
RETURNING id, username, name, bio, link, avatar, private, user_id, created_at, updated_at
`

type UpdateProfileParams struct {
	Username  string
	Name      sql.NullString
	Bio       sql.NullString
	Link      sql.NullString
	Avatar    sql.NullString
	Private   sql.NullInt64
	UpdatedAt string
	UserID    int64
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.Username,
		arg.Name,
		arg.Bio,
		arg.Link,
		arg.Avatar,
		arg.Private,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Bio,
		&i.Link,
		&i.Avatar,
		&i.Private,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfileAvatar = `-- name: UpdateProfileAvatar :one
UPDATE profiles 
SET avatar = ?, updated_at = ? 
WHERE user_id = ? 
RETURNING id, username, name, bio, link, avatar, private, user_id, created_at, updated_at
`

type UpdateProfileAvatarParams struct {
	Avatar    sql.NullString
	UpdatedAt string
	UserID    int64
}

func (q *Queries) UpdateProfileAvatar(ctx context.Context, arg UpdateProfileAvatarParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfileAvatar, arg.Avatar, arg.UpdatedAt, arg.UserID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Bio,
		&i.Link,
		&i.Avatar,
		&i.Private,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
