// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package relationships

import ()

type Relationship struct {
	ID         int64
	FollowerID int64
	FolloweeID int64
	CreatedAt  string
	UpdatedAt  string
	Foreign    interface{}
}
