package database

import (
	"context"
	"database/sql"
	"fmt"
	"log"
)

var DB *sql.DB     // Global Database Connection
var Query *Queries // Global Query to allow access to the database

// Database Connection Code
func Connect() *sql.DB {
	db, err := sql.Open("sqlite3", "./database/sqlite3.db")
	if err != nil {
		log.Fatal(err)
	}

	if err = db.Ping(); err != nil {
		log.Fatalf("Cannot ping database because %s", err)
	}

	fmt.Println("Database Connected Successfully")
	DB = db
	return db
}

func NewQueries() *Queries {
	return New(DB)
}

// DBTX is an interface that matches *sql.DB and *sql.Tx - Generated by SQLC
type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}
