// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package users

import (
	"context"
)

const getUserFromID = `-- name: GetUserFromID :one
SELECT id, username, email, password, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserFromID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
