// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package relationships

import (
	"context"
)

const createFollower = `-- name: CreateFollower :one
INSERT INTO relationships (follower_id, followee_id, created_at, updated_at) 
VALUES (?, ?, ?, ?)
RETURNING id, follower_id, followee_id, created_at, updated_at, "foreign"
`

type CreateFollowerParams struct {
	FollowerID int64
	FolloweeID int64
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) CreateFollower(ctx context.Context, arg CreateFollowerParams) (Relationship, error) {
	row := q.db.QueryRowContext(ctx, createFollower,
		arg.FollowerID,
		arg.FolloweeID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.FollowerID,
		&i.FolloweeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Foreign,
	)
	return i, err
}
