// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package auth

import ()

type User struct {
	ID        int64
	Uuid      string
	Username  string
	Email     string
	Password  string
	CreatedAt string
	UpdatedAt string
}
