// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package profiles

import (
	"database/sql"
)

type Profile struct {
	ID        int64
	Name      sql.NullString
	Bio       sql.NullString
	Link      sql.NullString
	Avatar    sql.NullString
	UserID    int64
	CreatedAt string
	UpdatedAt string
}
