// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package threads

import (
	"database/sql"
)

type Thread struct {
	ID        int64
	Content   string
	ThreadID  sql.NullInt64
	UserID    int64
	CreatedAt string
	UpdatedAt string
	Foreign   interface{}
}
